Fix docker installed & add MIT license
appwrite/docker-flutter pull request #8
Opened 2021-10-06 16:24 UTC by torn4dom4n

- Update links are broken
- Add MIT license

2021-10-06 21:07 UTC, stijnvdkolk commented on README.md
> +* [Windows](https://docs.docker.com/desktop/windows/install/)
Any reason for the new ordering?

2021-10-06 23:30 UTC, torn4dom4n commented on README.md
> +* [Windows](https://docs.docker.com/desktop/windows/install/)
I made a mistaken. I'm going to use the alphabet to sort it. Sorry 😂.

2021-10-07 18:14 UTC, stijnvdkolk approved these changes

2021-10-27 12:33 UTC, Meldiron requested changes
Requested tiny change

2021-10-27 12:33 UTC, Meldiron commented on README.md
> +License under the [MIT](LICENSE) license.
```suggestion
The MIT License (MIT) [http://www.opensource.org/licenses/mit-license.php](http://www.opensource.org/licenses/mit-license.php)
```

2021-10-31 08:10 UTC, christyjacob4 approved these changes

2021-10-31 08:10 UTC, merged

2021-10-31 08:10 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)